#!/bin/sh

. /lib/partman/lib/base.sh

dev=${1%//*}
oldid=${1#*//}

encryptid=""

cd $dev
disable_swap "$dev"

# ----------start---------
# edit by kobe to delete /encrypt partition
writedev=`echo \`fdisk -l | sed -n '/^\/dev/p' | cut -c1-10,53-54 | sed -n '/71/p'\` | cut -c1-10 | sed 's/ .*$//'`
if [ -n "$writedev" ]; then
    open_dialog PARTITIONS
    while :; do
        read_line num id size type fs path name
        if [ "$path" = "$writedev" ]; then
            encryptid="$id"
            break
        fi
    done
    close_dialog
    if [ -n "$encryptid" ]; then
        open_dialog DELETE_PARTITION $encryptid
        close_dialog
    fi
fi
#---------end---------

open_dialog DELETE_PARTITION $oldid
close_dialog
bestsize=0
bestid=
open_dialog PARTITIONS
while :; do
	read_line num id size type fs path name
	[ "$id" ] || break
	if [ "$fs" = free ] && longint_le $bestsize $size; then
		bestsize=$size
		bestid=$id
	fi
done
close_dialog

db_progress STOP

[ -z "$bestid" ] && exit 1
autopartition $dev $bestid || exit $?
exit 100
